export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_LOAD_SUCCESS = "LOGIN_LOAD_SUCCESS";
export const LOGIN_LOAD_FAIL = "LOGIN_LOAD_FAIL";

export const LOGOUT = "LOGOUT";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_LOAD_SUCCESS = "REGISTER_LOAD_SUCCESS";
export const REGISTER_LOAD_FAIL = "REGISTER_LOAD_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const LOADING_CREATED_PROGRAMS = "LOADING_CREATED_PROGRAMS";
export const LOAD_CREATED_PROGRAMS_SUCCESS = "LOAD_CREATED_PROGRAMS_SUCCESS";
export const LOAD_CREATED_PROGRAMS_FAIL = "LOAD_CREATED_PROGRAMS_FAIL";
